spring:
  datasource:
    url: ${PGDB_URL}
    username: ${PGDB_USERNAME}
    password: ${PGDB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
  jackson:
    deserialization:
      fail-on-unknown-properties: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

findex:
  api:
    key: ${API_KEY}
    sync_cron: "0 1 15 * * *"


