spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jackson:
    deserialization:
      fail-on-unknown-properties: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

findex:
  api:
    key: ${API_KEY}
    sync_cron: "0 1 15 * * *"

server:
  port: ${PORT:8080} #Railway 포트설정

